# Generated by Django 3.2.7 on 2022-12-23 07:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_productcategoryfaq_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='web_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
