# Generated by Django 3.2.7 on 2022-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='password',
            field=models.CharField(default='dfghjk', max_length=100),
        ),
    ]
